flags:
  mintty:
    win32-2-5-3: false
packages:
- .
extra-deps:
- QuickCheck-2.11.3
- ansi-terminal-0.8.0.4
- colour-2.3.4
- mintty-0.1.2
- primitive-0.6.4.0
- random-1.1
- tf-random-0.5
resolver: ghc-8.0.2
