flags:
  mintty:
    win32-2-5-3: false
  transformers-compat:
    five: true
  time-locale-compat:
    old-locale: false
packages:
- .
extra-deps:
- HTTP-4000.3.12
- aeson-1.4.0.0
- ansi-terminal-0.8.0.4
- appar-0.1.4
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.2.1
- attoparsec-0.13.2.2
- auto-update-0.1.4
- base-compat-0.10.1
- base-orphans-0.7
- base64-bytestring-1.0.0.1
- basement-0.0.7
- blaze-builder-0.4.1.0
- bsb-http-chunked-0.0.0.2
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- bytestring-lexing-0.5.0.2
- case-insensitive-1.2.0.11
- cereal-0.5.5.0
- colour-2.3.4
- conduit-1.3.0.2
- conduit-extra-1.3.0
- cookie-0.4.4
- cryptonite-0.25
- data-default-class-0.1.2.0
- dlist-0.8.0.4
- easy-file-0.2.2
- errors-2.3.0
- exceptions-0.10.0
- fail-4.9.0.0
- fast-logger-2.4.11
- foundation-0.0.20
- hashable-1.2.7.0
- hedis-0.10.2
- hourglass-0.2.11
- http-date-0.0.7
- http-types-0.12.1
- http2-1.6.3
- integer-logarithms-1.0.2.1
- iproute-1.7.5
- lifted-base-0.2.3.12
- memory-0.14.16
- mintty-0.1.2
- monad-control-1.0.2.3
- mono-traversable-1.0.8.1
- mtl-2.2.2
- nats-1.1.2
- network-2.7.0.0
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- parsec-3.1.13.0
- pem-0.2.4
- primitive-0.6.4.0
- psqueues-0.2.7.0
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resourcet-1.2.1
- safe-0.3.17
- scanner-0.2
- scientific-0.3.6.2
- scotty-0.11.1
- semigroups-0.18.4
- simple-sendfile-0.2.27
- split-0.2.3.3
- stm-2.4.5.0
- streaming-commons-0.2.0.0
- stringsearch-0.3.6.6
- tagged-0.8.5
- text-1.2.3.0
- th-abstraction-0.2.7.0
- time-locale-compat-0.1.1.4
- tls-1.4.1
- transformers-base-0.4.5.2
- transformers-compat-0.6.2
- typed-process-0.2.2.0
- unix-compat-0.4.3.1
- unliftio-core-0.1.1.0
- unordered-containers-0.2.9.0
- uuid-types-1.0.3
- vault-0.3.1.1
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- void-0.7.2
- wai-3.2.1.2
- wai-extra-3.0.22.1
- wai-logger-2.3.2
- warp-3.2.22
- word8-0.1.3
- x509-1.7.3
- x509-store-1.6.6
- x509-validation-1.6.10
- zlib-0.6.2
resolver: ghc-8.0.2
