flags:
  transformers-compat:
    five: true
packages:
- .
extra-deps:
- QuickCheck-2.11.3
- StateVar-1.1.1.0
- base-orphans-0.7
- bifunctors-5.5.2
- cabal-doctest-1.0.6
- checkers-0.4.10
- comonad-5.0.3
- contravariant-1.4.1
- distributive-0.5.3
- hashable-1.2.7.0
- primitive-0.6.4.0
- random-1.1
- semigroupoids-5.2.2
- semigroups-0.18.4
- stm-2.4.5.0
- tagged-0.8.5
- text-1.2.3.0
- tf-random-0.5
- th-abstraction-0.2.7.0
- transformers-compat-0.6.2
- unordered-containers-0.2.9.0
resolver: ghc-8.0.2
