flags:
  mintty:
    win32-2-5-3: false
  transformers-compat:
    five: true
packages:
- .
extra-deps:
- StateVar-1.1.1.0
- adjunctions-4.4
- ansi-terminal-0.8.0.4
- ansi-wl-pprint-0.6.8.2
- attoparsec-0.13.2.2
- base-orphans-0.8
- bifunctors-5.5.3
- blaze-builder-0.4.1.0
- blaze-html-0.9.1.1
- blaze-markup-0.8.2.1
- cabal-doctest-1.0.6
- call-stack-0.1.0
- charset-0.3.7.1
- colour-2.3.4
- comonad-5.0.4
- contravariant-1.5
- distributive-0.6
- exceptions-0.10.0
- fingertree-0.1.4.1
- free-5.1
- hashable-1.2.7.0
- integer-logarithms-1.0.2.1
- invariant-0.5
- kan-extensions-5.2
- lens-4.17
- mintty-0.1.2
- mtl-2.2.2
- parallel-3.2.1.1
- parsec-3.1.13.0
- parsers-0.12.9
- primitive-0.6.4.0
- profunctors-5.3
- reducers-3.12.3
- reflection-2.1.4
- scientific-0.3.6.2
- semigroupoids-5.3.1
- semigroups-0.18.5
- stm-2.4.5.0
- tagged-0.8.6
- text-1.2.3.0
- th-abstraction-0.2.8.0
- transformers-base-0.4.5.2
- transformers-compat-0.6.2
- trifecta-2
- unordered-containers-0.2.9.0
- utf8-string-1.0.1.1
- vector-0.12.0.1
- void-0.7.2
resolver: ghc-8.0.2
